### ISSUE TITLE
missing cellosaurus ids

### ISSUE THREAD

**Issue by quevedor2** [BHKLAB-Pachyderm/Annotations#1]
File: cell_annotation_all.csv

- unique.cellid: D-245M is missing cellosaurus annotation CVCL_1152
- unique.cellid: U266B1 is missing cellosaurus annotation CVCL_0566

Line 257  unique.cellid is HEC-1 but contains CCLE's HEC-1-B
Line 1321 unique.cellid is HEC-1-B but is missing CCLE's.  (Cellosaurus says HEC-1 = HEC-B, but not HEC-1-B)

**Comment by imanthonny** [comment]
Just pushed fix. Thanks
